### ISSUE TITLE
adding this to minecraft wiki, edit entry as needed

### ISSUE THREAD

**Issue by pokeball99** [M4GNV5/ArmorstandAnimator#1]
http://minecraft.gamepedia.com/Programs_and_editors/Specialized_programs

**Comment by WebFreak001** [comment]
we dont really have started yet :P

**Comment by M4GNV5** [comment]
thanks but at the moment there is nothing you can do with it :grinning:

**Comment by M4GNV5** [comment]
i removed it from minecraft wiki until we got stuff to show ;)
thanks anyways :smiley:
